# This file is an example config file

name: 'example'
model:
  name: 'Helsinki-NLP/opus-mt-de-en'
  type: 'MarianMT'
dataset:
  name: 'tatoeba'
  source: 'de'
  target: 'en'
metrics:
  - {
      name: "sacreblue"
  }



