# This file is an example config file

name: 'finetuned'
model:
  name: './data/finetuned'
  type: 'MarianMT'
dataset:
  name: 'tatoeba'
  source: 'de'
  target: 'en'
metrics:
  - {
      name: "sacreblue"
  }



