# This file is an example config file

nmt_config: './configs/nmt/helsinki-taboeta-de-en.yml'



# Copies the structure of the NTM config, is used for loading the NMT model
nmt_model:
  model:
    name: 'Helsinki-NLP/opus-mt-de-en'
    checkpoint: 'data/tatoeba-MLE-1'
    type: 'MarianMT'

dataset:
  name: 'develop'


