
nmt_config: './configs/nmt/helsinki-taboeta-de-en.yml'



# Copies the structure of the NTM config, is used for loading the NMT model


dataset:
  base_dir: './trained_models/NMT/tatoeba-de-en/data/'
  preprocess_dir: './trained_models/predictive/tatoeba-de-en/data/'
  sampling_method: 'ancestral'
  n_hypothesis: 10
  n_references: 100



predictive_model:
  layers:
    - 2048
    - 1024
    - 512
    - 256
    - 128
    - 1
  activation_function: 'silu'
  dropout: 0.25
  weight_decay: 0.9
  type: 'MSE'

  features:
    - 'avg_pool_encoder_hidden_state'
    - 'avg_pool_decoder_hidden_state'
    - 'max_pool_encoder_hidden_state'
    - 'max_pool_decoder_hidden_state'

  nmt_model:
    model:
      name: 'Helsinki-NLP/opus-mt-de-en'
      checkpoint: 'C:\Users\gerso\projects\master-thesis/data/tatoeba-MLE-1'
      type: 'MarianMT'
